apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-demo-app-chart.fullname" . }}
  labels:
    {{- include "k8s-demo-app-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "k8s-demo-app-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "k8s-demo-app-chart.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: K8S_DEMO_APP_MESSAGE
              value: {{ .Values.k8sDemoAppMessage }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
