{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-demo-app-chart.fullname" . }}
  labels:
    {{- include "k8s-demo-app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "k8s-demo-app-chart.name" . }}
{{- end }}