apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "k8s-demo-app-chart.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "k8s-demo-app-chart.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  behavior:
    scaleUp:
      policies:
{{- range .Values.hpa.behavior.scaleUp.policies }}
        - type: {{ .type }}
          value: {{ .value }}
          periodSeconds: {{ .periodSeconds }}
{{- end }}
      stabilizationWindowSeconds: {{ .Values.hpa.behavior.scaleUp.stabilizationWindowSeconds }}
    scaleDown:
      policies:
{{- range .Values.hpa.behavior.scaleDown.policies }}
        - type: {{ .type }}
          value: {{ .value }}
          periodSeconds: {{ .periodSeconds }}
{{- end }}
      stabilizationWindowSeconds: {{ .Values.hpa.behavior.scaleDown.stabilizationWindowSeconds }}
  metrics:
{{- range .Values.hpa.metrics }}
    - type: {{ .type }}
      {{ .type }}:
        name: {{ .resource.name }}
        target:
          type: {{ .resource.target.type }}
          averageUtilization: {{ .resource.target.averageUtilization }}
{{- end }}
