apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn:  arn:aws:iam::895879716483:role/aws-load-balancer-controller-eks-joshua-schell
{{ toYaml .Values.annotations | indent 4 }}
